"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-17 02:51:31.997178

Creates every table in ``docs/architecture/backend-contracts.md`` section 2,
plus role grants for the runtime (``linesense_app``) role. The role name is
resolved from ``-x app_role=...`` on the command line, else
``LS_APP_DB_ROLE``, else ``linesense_app`` (see ``_app_role`` below).

Grants are **not** made automatic via ``ALTER DEFAULT PRIVILEGES``: every
future migration that adds a table must explicitly grant on it (see the
grants block at the end of ``upgrade()`` for the exact statements to repeat).
"""

import os
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _app_role() -> str:
    cli_arg = context.get_x_argument(as_dictionary=True).get("app_role")
    if cli_arg:
        return cli_arg
    return os.environ.get("LS_APP_DB_ROLE", "linesense_app")


def _create_extensions() -> None:
    """``CREATE EXTENSION IF NOT EXISTS`` guarded by an existence check.

    ``scripts/dev-db.sh`` already creates ``vector`` and ``pg_trgm`` as the
    cluster superuser, so this is normally a no-op; wrapping it in a
    ``pg_extension`` check first means the statement never even attempts to
    run (and so never needs extension-creation privilege) when the extension
    is already present, which keeps it safe to run as ``linesense_owner``.
    """
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
                CREATE EXTENSION vector;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
                CREATE EXTENSION pg_trgm;
            END IF;
        END
        $$;
        """
    )


def _grant_app_role_privileges() -> None:
    role = _app_role()
    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "{role}"')
    op.execute(f'REVOKE UPDATE, DELETE ON audit_events FROM "{role}"')
    op.execute(f'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "{role}"')


def upgrade() -> None:
    """Upgrade schema."""
    _create_extensions()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("factory_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'SERVICE', 'SYSTEM')",
            name=op.f("ck_audit_events_actor_type_valid"),
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'DENIED', 'FAILED')", name=op.f("ck_audit_events_outcome_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_organization_id_factory_id",
        "audit_events",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_organization_id_created_at",
        "audit_events",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "available_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("leased_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('READY', 'LEASED', 'DONE', 'FAILED', 'CANCELLED')",
            name=op.f("ck_jobs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_jobs_dedupe_key")),
    )
    op.create_index(
        "ix_jobs_queue_status_available_at",
        "jobs",
        ["queue", "status", "available_at"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("issuer", "subject", name="uq_users_issuer_subject"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_customers_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("organization_id", "code", name="uq_customers_organization_id_code"),
    )
    op.create_table(
        "factories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), server_default="Asia/Colombo", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_factories_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factories")),
        sa.UniqueConstraint("organization_id", "code", name="uq_factories_organization_id_code"),
        sa.UniqueConstraint("organization_id", "id", name="uq_factories_organization_id_id"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_idempotency_keys_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "organization_id",
            "actor_id",
            "operation",
            "key",
            name="uq_idempotency_keys_organization_id_actor_id_operation_key",
        ),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("safety_stock", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "unit IN ('m', 'kg', 'pcs', 'cone')", name=op.f("ck_materials_unit_valid")
        ),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_materials_lead_time_days_non_negative")
        ),
        sa.CheckConstraint(
            "pack_size IS NULL OR pack_size > 0", name=op.f("ck_materials_pack_size_positive")
        ),
        sa.CheckConstraint(
            "safety_stock >= 0", name=op.f("ck_materials_safety_stock_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_materials_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("organization_id", "code", name="uq_materials_organization_id_code"),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_memberships_organization_id_user_id"
        ),
    )
    op.create_table(
        "quality_policy_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'RETIRED')",
            name=op.f("ck_quality_policy_versions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_quality_policy_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quality_policy_versions_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_policy_versions")),
        sa.UniqueConstraint(
            "organization_id",
            "code",
            "version_no",
            name="uq_quality_policy_versions_organization_id_code_version_no",
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("csrf_token", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_table(
        "styles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("product_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_styles_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_styles")),
        sa.UniqueConstraint("organization_id", "code", name="uq_styles_organization_id_code"),
    )
    op.create_table(
        "bom_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_bom_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_bom_versions_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_versions")),
        sa.UniqueConstraint("style_id", "version_no", name="uq_bom_versions_style_id_version_no"),
    )
    op.create_index(
        "uq_bom_versions_one_active_per_style",
        "bom_versions",
        ["style_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("doc_type", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "doc_type IN ('SOP', 'QUALITY_POLICY', 'IE_STANDARD', 'OTHER')",
            name=op.f("ck_documents_doc_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_documents_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_documents_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_documents_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_documents_organization_id_slug"),
    )
    op.create_index(
        "ix_documents_organization_id_factory_id",
        "documents",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "expected_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=False),
        sa.Column("supplier_ref", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'RECEIVED', 'CANCELLED')",
            name=op.f("ck_expected_receipts_status_valid"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_expected_receipts_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_expected_receipts_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_expected_receipts_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_expected_receipts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expected_receipts")),
    )
    op.create_index(
        "ix_expected_receipts_organization_id_factory_id",
        "expected_receipts",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("file_sha256", sa.Text(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("preview", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('VALIDATED', 'COMMITTED', 'REJECTED')",
            name=op.f("ck_import_batches_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_import_batches_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_import_batches_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_import_batches_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        "ix_import_batches_organization_id_factory_id",
        "import_batches",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index(
        "uq_import_batches_organization_id_kind_file_sha256",
        "import_batches",
        ["organization_id", "kind", "file_sha256"],
        unique=True,
        postgresql_where=sa.text("status = 'COMMITTED'"),
    )
    op.create_table(
        "lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("operator_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("operator_count > 0", name=op.f("ck_lines_operator_count_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_lines_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lines_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lines")),
        sa.UniqueConstraint("factory_id", "code", name="uq_lines_factory_id_code"),
    )
    op.create_index(
        "ix_lines_organization_id_factory_id",
        "lines",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "material_balances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("on_hand_accepted", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reserved", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "on_hand_accepted >= 0", name=op.f("ck_material_balances_on_hand_accepted_non_negative")
        ),
        sa.CheckConstraint(
            "reserved <= on_hand_accepted",
            name=op.f("ck_material_balances_reserved_within_on_hand"),
        ),
        sa.CheckConstraint(
            "reserved >= 0", name=op.f("ck_material_balances_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_balances_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_material_balances_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_material_balances_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_balances")),
        sa.UniqueConstraint(
            "factory_id", "material_id", name="uq_material_balances_factory_id_material_id"
        ),
    )
    op.create_index(
        "ix_material_balances_organization_id_factory_id",
        "material_balances",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "material_lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("lot_code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUARANTINE', 'ACCEPTED', 'REJECTED')",
            name=op.f("ck_material_lots_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_material_lots_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_material_lots_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_material_lots_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_lots")),
        sa.UniqueConstraint("factory_id", "lot_code", name="uq_material_lots_factory_id_lot_code"),
    )
    op.create_index(
        "ix_material_lots_organization_id_factory_id",
        "material_lots",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_notes_author_id_users")),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_notes_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notes_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(
        "ix_notes_organization_id_factory_id",
        "notes",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_notifications_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_organization_id_factory_id",
        "notifications",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("membership_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('org_admin', 'supervisor', 'planner', 'storekeeper', "
            "'ie_engineer', 'quality_manager', 'viewer')",
            name=op.f("ck_role_assignments_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"], ["factories.id"], name=op.f("fk_role_assignments_factory_id_factories")
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_role_assignments_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint(
            "membership_id",
            "factory_id",
            "role",
            name="uq_role_assignments_membership_id_factory_id_role",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "style_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sam_minutes", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("skill_code", sa.Text(), nullable=False),
        sa.Column("machine_type", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "sam_minutes > 0", name=op.f("ck_style_operations_sam_minutes_positive")
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_style_operations_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_style_operations")),
        sa.UniqueConstraint("style_id", "sequence", name="uq_style_operations_style_id_sequence"),
    )
    op.create_table(
        "bom_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bom_version_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity_per_unit", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("wastage_fraction", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.CheckConstraint(
            "quantity_per_unit > 0", name=op.f("ck_bom_lines_quantity_per_unit_positive")
        ),
        sa.CheckConstraint(
            "wastage_fraction >= 0 AND wastage_fraction < 1",
            name=op.f("ck_bom_lines_wastage_fraction_range"),
        ),
        sa.ForeignKeyConstraint(
            ["bom_version_id"],
            ["bom_versions.id"],
            name=op.f("fk_bom_lines_bom_version_id_bom_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_bom_lines_material_id_materials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_lines")),
    )
    op.create_table(
        "document_acl",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_acl_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_acl")),
        sa.UniqueConstraint("document_id", "role", name="uq_document_acl_document_id_role"),
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('QUARANTINE', 'PROCESSING', 'ACTIVE', 'REJECTED', 'SUPERSEDED')",
            name=op.f("ck_document_versions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_document_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version_no", name="uq_document_versions_document_id_version_no"
        ),
    )
    op.create_index(
        "ix_document_versions_document_id_status",
        "document_versions",
        ["document_id", "status"],
        unique=False,
    )
    op.create_table(
        "import_errors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("field", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_errors_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_errors")),
    )
    op.create_table(
        "line_capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("skill_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["lines.id"],
            name=op.f("fk_line_capabilities_line_id_lines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_capabilities")),
        sa.UniqueConstraint(
            "line_id", "skill_code", name="uq_line_capabilities_line_id_skill_code"
        ),
    )
    op.create_table(
        "line_capacity_slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("shift_code", sa.Text(), nullable=False),
        sa.Column("available_operator_minutes", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("planned_efficiency", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "allocated_standard_minutes",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "shift_code IN ('A', 'B')", name=op.f("ck_line_capacity_slots_shift_code_valid")
        ),
        sa.CheckConstraint(
            "allocated_standard_minutes <= available_operator_minutes * planned_efficiency",
            name=op.f("ck_line_capacity_slots_allocated_within_capacity"),
        ),
        sa.CheckConstraint(
            "allocated_standard_minutes >= 0",
            name=op.f("ck_line_capacity_slots_allocated_standard_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "available_operator_minutes >= 0",
            name=op.f("ck_line_capacity_slots_available_operator_minutes_non_negative"),
        ),
        sa.CheckConstraint(
            "planned_efficiency > 0 AND planned_efficiency <= 1",
            name=op.f("ck_line_capacity_slots_planned_efficiency_range"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_line_capacity_slots_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_line_capacity_slots_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_line_capacity_slots_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_capacity_slots")),
        sa.UniqueConstraint(
            "line_id",
            "slot_date",
            "shift_code",
            name="uq_line_capacity_slots_line_id_slot_date_shift_code",
        ),
    )
    op.create_index(
        "ix_line_capacity_slots_organization_id_factory_id",
        "line_capacity_slots",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "line_measurements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("measured_on", sa.Date(), nullable=False),
        sa.Column("hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("units_output", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("hours > 0", name=op.f("ck_line_measurements_hours_positive")),
        sa.CheckConstraint(
            "units_output >= 0", name=op.f("ck_line_measurements_units_output_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_line_measurements_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_line_measurements_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_line_measurements_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_line_measurements_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_measurements")),
    )
    op.create_index(
        "ix_line_measurements_organization_id_factory_id",
        "line_measurements",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "operation_staffing",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("parallel_operators", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "parallel_operators > 0", name=op.f("ck_operation_staffing_parallel_operators_positive")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_operation_staffing_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["style_operations.id"],
            name=op.f("fk_operation_staffing_operation_id_style_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_operation_staffing_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_operation_staffing_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_operation_staffing_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_staffing")),
        sa.UniqueConstraint(
            "line_id",
            "style_id",
            "operation_id",
            name="uq_operation_staffing_line_id_style_id_operation_id",
        ),
    )
    op.create_index(
        "ix_operation_staffing_organization_id_factory_id",
        "operation_staffing",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "operator_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("alias_code", sa.Text(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_operator_aliases_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_operator_aliases_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_operator_aliases_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_aliases")),
        sa.UniqueConstraint(
            "factory_id", "alias_code", name="uq_operator_aliases_factory_id_alias_code"
        ),
    )
    op.create_index(
        "ix_operator_aliases_organization_id_factory_id",
        "operator_aliases",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("bom_version_id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("produced_units", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("packed_units", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("production_state", sa.Text(), nullable=False),
        sa.Column("material_state", sa.Text(), nullable=False),
        sa.Column("quality_state", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "material_state IN ('UNKNOWN', 'READY', 'AT_RISK', 'SHORTAGE')",
            name=op.f("ck_orders_material_state_valid"),
        ),
        sa.CheckConstraint(
            "production_state IN ('DRAFT', 'VALIDATED', 'PLANNED', 'IN_PRODUCTION', "
            "'PRODUCTION_COMPLETE', 'DISPATCHED', 'CANCELLED')",
            name=op.f("ck_orders_production_state_valid"),
        ),
        sa.CheckConstraint(
            "quality_state IN ('NOT_INSPECTED', 'PENDING', 'HOLD', 'RELEASED')",
            name=op.f("ck_orders_quality_state_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'csv_import', 'synthetic_seed')",
            name=op.f("ck_orders_source_valid"),
        ),
        sa.CheckConstraint("packed_units >= 0", name=op.f("ck_orders_packed_units_non_negative")),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_orders_priority_range")),
        sa.CheckConstraint(
            "produced_units >= 0", name=op.f("ck_orders_produced_units_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["bom_version_id"],
            ["bom_versions.id"],
            name=op.f("fk_orders_bom_version_id_bom_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_orders_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_orders_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_orders_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_orders_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "organization_id", "external_ref", name="uq_orders_organization_id_external_ref"
        ),
    )
    op.create_index(
        "ix_orders_factory_id_due_date", "orders", ["factory_id", "due_date"], unique=False
    )
    op.create_index(
        "ix_orders_organization_id_factory_id",
        "orders",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("replan_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("model_calls_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("model_calls_limit", sa.Integer(), server_default=sa.text("12"), nullable=False),
        sa.Column("tokens_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("token_budget", sa.Integer(), server_default=sa.text("200000"), nullable=False),
        sa.Column("llm_provider", sa.Text(), nullable=False),
        sa.Column("llm_model", sa.Text(), nullable=False),
        sa.Column("degraded_reason", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("deadline_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'AWAITING_REVIEW', 'COMPLETED', "
            "'DEGRADED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_analysis_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_analysis_runs_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_analysis_runs_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_analysis_runs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_analysis_runs_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(
        "ix_analysis_runs_organization_id_factory_id",
        "analysis_runs",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(section, '') || ' ' || text)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_chunks_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_chunks_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_chunks_organization_id_factory_id_factories",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "document_version_id", "chunk_index", name="uq_chunks_document_version_id_chunk_index"
        ),
    )
    op.create_index(
        "ix_chunks_organization_id_factory_id",
        "chunks",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index("ix_chunks_tsv", "chunks", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "cycle_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("style_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("operator_alias_id", sa.UUID(), nullable=False),
        sa.Column("observed_seconds", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("observed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.UUID(), nullable=True),
        sa.Column("is_outlier", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("outlier_approved_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "observed_seconds > 0", name=op.f("ck_cycle_observations_observed_seconds_positive")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_cycle_observations_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["style_operations.id"],
            name=op.f("fk_cycle_observations_operation_id_style_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["operator_alias_id"],
            ["operator_aliases.id"],
            name=op.f("fk_cycle_observations_operator_alias_id_operator_aliases"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_cycle_observations_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cycle_observations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["outlier_approved_by"],
            ["users.id"],
            name=op.f("fk_cycle_observations_outlier_approved_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["users.id"], name=op.f("fk_cycle_observations_recorded_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["style_id"], ["styles.id"], name=op.f("fk_cycle_observations_style_id_styles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cycle_observations")),
    )
    op.create_index(
        "ix_cycle_observations_organization_id_factory_id",
        "cycle_observations",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=True),
        sa.Column("inspection_type", sa.Text(), nullable=False),
        sa.Column("inspected_units", sa.Integer(), nullable=False),
        sa.Column("defective_units", sa.Integer(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("inspected_by", sa.UUID(), nullable=True),
        sa.Column("inspected_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "inspection_type IN ('INLINE', 'FINAL')",
            name=op.f("ck_inspections_inspection_type_valid"),
        ),
        sa.CheckConstraint(
            "result IN ('PASS', 'FAIL', 'INSUFFICIENT_SAMPLE')",
            name=op.f("ck_inspections_result_valid"),
        ),
        sa.CheckConstraint(
            "defective_units <= inspected_units",
            name=op.f("ck_inspections_defective_units_within_inspected"),
        ),
        sa.CheckConstraint(
            "defective_units >= 0", name=op.f("ck_inspections_defective_units_non_negative")
        ),
        sa.CheckConstraint(
            "inspected_units >= 0", name=op.f("ck_inspections_inspected_units_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["inspected_by"], ["users.id"], name=op.f("fk_inspections_inspected_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["lines.id"], name=op.f("fk_inspections_line_id_lines")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_inspections_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_inspections_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_inspections_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["quality_policy_versions.id"],
            name=op.f("fk_inspections_policy_version_id_quality_policy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
    )
    op.create_index(
        "ix_inspections_organization_id_factory_id",
        "inspections",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "skill_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operator_alias_id", sa.UUID(), nullable=False),
        sa.Column("skill_code", sa.Text(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.CheckConstraint("level BETWEEN 1 AND 4", name=op.f("ck_skill_records_level_range")),
        sa.ForeignKeyConstraint(
            ["operator_alias_id"],
            ["operator_aliases.id"],
            name=op.f("fk_skill_records_operator_alias_id_operator_aliases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_records")),
        sa.UniqueConstraint(
            "operator_alias_id", "skill_code", name="uq_skill_records_operator_alias_id_skill_code"
        ),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=True),
        sa.Column("movement_type", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("corrects_movement_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(movement_type = 'RECEIPT' AND quantity > 0) OR "
            "(movement_type = 'ISSUE' AND quantity < 0) OR "
            "(movement_type = 'CORRECTION' AND quantity <> 0)",
            name=op.f("ck_stock_movements_quantity_sign_matches_movement_type"),
        ),
        sa.CheckConstraint(
            "movement_type IN ('RECEIPT', 'ISSUE', 'CORRECTION')",
            name=op.f("ck_stock_movements_movement_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["corrects_movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_movements_corrects_movement_id_stock_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_movements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"], ["material_lots.id"], name=op.f("fk_stock_movements_lot_id_material_lots")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_stock_movements_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_stock_movements_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_stock_movements_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_stock_movements_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        "ix_stock_movements_organization_id_factory_id",
        "stock_movements",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_factory_id_material_id_created_at",
        "stock_movements",
        ["factory_id", "material_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("sender", sa.Text(), nullable=False),
        sa.Column("recipient", sa.Text(), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "recipient IN ('planning', 'rm', 'ie', 'quality')",
            name=op.f("ck_agent_tasks_recipient_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_agent_tasks_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_agent_tasks_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_tasks_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_agent_tasks_parent_task_id_agent_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_agent_tasks_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tasks")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_agent_tasks_idempotency_key")),
        sa.UniqueConstraint("message_id", name=op.f("uq_agent_tasks_message_id")),
    )
    op.create_index(
        "ix_agent_tasks_organization_id_factory_id",
        "agent_tasks",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index("ix_agent_tasks_run_id", "agent_tasks", ["run_id"], unique=False)
    op.create_table(
        "defect_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("defect_code", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('MINOR', 'MAJOR', 'CRITICAL')",
            name=op.f("ck_defect_observations_severity_valid"),
        ),
        sa.CheckConstraint("count > 0", name=op.f("ck_defect_observations_count_positive")),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_defect_observations_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["style_operations.id"],
            name=op.f("fk_defect_observations_operation_id_style_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defect_observations")),
    )
    op.create_table(
        "quality_holds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_by", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("release_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RELEASED')", name=op.f("ck_quality_holds_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_quality_holds_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_quality_holds_inspection_id_inspections"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_quality_holds_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_quality_holds_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quality_holds_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["released_by"], ["users.id"], name=op.f("fk_quality_holds_released_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_holds")),
    )
    op.create_index(
        "ix_quality_holds_organization_id_factory_id",
        "quality_holds",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "quality_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("released_by", sa.UUID(), nullable=False),
        sa.Column("released_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_quality_releases_inspection_id_inspections"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_quality_releases_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_quality_releases_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quality_releases_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["quality_policy_versions.id"],
            name=op.f("fk_quality_releases_policy_version_id_quality_policy_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["released_by"], ["users.id"], name=op.f("fk_quality_releases_released_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_releases")),
    )
    op.create_index(
        "ix_quality_releases_organization_id_factory_id",
        "quality_releases",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal_hash", sa.Text(), nullable=False),
        sa.Column("input_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by", sa.Text(), nullable=False),
        sa.Column("proposed_by_agent", sa.Text(), nullable=False),
        sa.Column("proposer_user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("applied_by", sa.UUID(), nullable=True),
        sa.Column("applied_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("superseded_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generated_by IN ('deterministic', 'model')",
            name=op.f("ck_recommendations_generated_by_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('ALLOCATION', 'RESERVATION', 'ALLOCATION_AND_RESERVATION')",
            name=op.f("ck_recommendations_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PROPOSED', 'APPROVED', 'REJECTED', "
            "'EXPIRED', 'APPLIED', 'SUPERSEDED')",
            name=op.f("ck_recommendations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["applied_by"], ["users.id"], name=op.f("fk_recommendations_applied_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_recommendations_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_recommendations_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recommendations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["proposer_user_id"],
            ["users.id"],
            name=op.f("fk_recommendations_proposer_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_recommendations_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        "ix_recommendations_organization_id_factory_id",
        "recommendations",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_factory_id_status",
        "recommendations",
        ["factory_id", "status"],
        unique=False,
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_run_events_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
    )
    op.create_index("ix_run_events_run_id_id", "run_events", ["run_id", "id"], unique=False)
    op.create_table(
        "run_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("input_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_run_snapshots_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_run_snapshots_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_run_snapshots_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_run_snapshots_run_id_analysis_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_snapshots")),
    )
    op.create_index(
        "ix_run_snapshots_organization_id_factory_id",
        "run_snapshots",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "agent_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.id"], name=op.f("fk_agent_results_run_id_analysis_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["agent_tasks.id"], name=op.f("fk_agent_results_task_id_agent_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_results")),
        sa.UniqueConstraint("task_id", name=op.f("uq_agent_results_task_id")),
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("slot_id", sa.UUID(), nullable=False),
        sa.Column("standard_minutes", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("units", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RELEASED')", name=op.f("ck_allocations_status_valid")
        ),
        sa.CheckConstraint(
            "standard_minutes > 0", name=op.f("ck_allocations_standard_minutes_positive")
        ),
        sa.CheckConstraint("units > 0", name=op.f("ck_allocations_units_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_allocations_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_allocations_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_allocations_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_allocations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_allocations_recommendation_id_recommendations"),
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["line_capacity_slots.id"],
            name=op.f("fk_allocations_slot_id_line_capacity_slots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(
        "ix_allocations_organization_id_factory_id",
        "allocations",
        ["organization_id", "factory_id"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("proposal_hash", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('APPROVED', 'REJECTED')", name=op.f("ck_approvals_decision_valid")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_approvals_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_approvals_recommendation_id_recommendations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("recommendation_id", name=op.f("uq_approvals_recommendation_id")),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RELEASED', 'CONSUMED')",
            name=op.f("ck_reservations_status_valid"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_reservations_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_reservations_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_reservations_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_reservations_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "factory_id"],
            ["factories.organization_id", "factories.id"],
            name="fk_reservations_organization_id_factory_id_factories",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reservations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_reservations_recommendation_id_recommendations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(
        "ix_reservations_organization_id_factory_id",
        "reservations",
        ["organization_id", "factory_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Deferred foreign keys for the two genuine table-creation cycles
    # (see the module docstrings of app/db/models/workflow.py and
    # app/db/models/quality.py). `op.create_table`'s inline
    # `use_alter=True` markers are metadata-only for autogenerate's benefit
    # and are never actually emitted as DDL by `op.create_table`, so these
    # constraints must be added explicitly once both tables exist.
    op.create_foreign_key(
        "fk_analysis_runs_snapshot_id_run_snapshots",
        "analysis_runs",
        "run_snapshots",
        ["snapshot_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_quality_holds_release_id_quality_releases",
        "quality_holds",
        "quality_releases",
        ["release_id"],
        ["id"],
    )

    _grant_app_role_privileges()


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the two deferred foreign keys added at the end of upgrade()
    # first, since they would otherwise block dropping the tables they
    # point at (run_snapshots, quality_releases) below.
    op.drop_constraint(
        "fk_analysis_runs_snapshot_id_run_snapshots", "analysis_runs", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_quality_holds_release_id_quality_releases", "quality_holds", type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reservations_organization_id_factory_id", table_name="reservations")
    op.drop_table("reservations")
    op.drop_table("approvals")
    op.drop_index("ix_allocations_organization_id_factory_id", table_name="allocations")
    op.drop_table("allocations")
    op.drop_table("agent_results")
    op.drop_index("ix_run_snapshots_organization_id_factory_id", table_name="run_snapshots")
    op.drop_table("run_snapshots")
    op.drop_index("ix_run_events_run_id_id", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_recommendations_factory_id_status", table_name="recommendations")
    op.drop_index("ix_recommendations_organization_id_factory_id", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("ix_quality_releases_organization_id_factory_id", table_name="quality_releases")
    op.drop_table("quality_releases")
    op.drop_index("ix_quality_holds_organization_id_factory_id", table_name="quality_holds")
    op.drop_table("quality_holds")
    op.drop_table("defect_observations")
    op.drop_index("ix_agent_tasks_run_id", table_name="agent_tasks")
    op.drop_index("ix_agent_tasks_organization_id_factory_id", table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(
        "ix_stock_movements_factory_id_material_id_created_at", table_name="stock_movements"
    )
    op.drop_index("ix_stock_movements_organization_id_factory_id", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_table("skill_records")
    op.drop_index("ix_inspections_organization_id_factory_id", table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(
        "ix_cycle_observations_organization_id_factory_id", table_name="cycle_observations"
    )
    op.drop_table("cycle_observations")
    op.drop_index("ix_chunks_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index("ix_chunks_organization_id_factory_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_analysis_runs_organization_id_factory_id", table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index("ix_orders_organization_id_factory_id", table_name="orders")
    op.drop_index("ix_orders_factory_id_due_date", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_operator_aliases_organization_id_factory_id", table_name="operator_aliases")
    op.drop_table("operator_aliases")
    op.drop_index(
        "ix_operation_staffing_organization_id_factory_id", table_name="operation_staffing"
    )
    op.drop_table("operation_staffing")
    op.drop_index("ix_line_measurements_organization_id_factory_id", table_name="line_measurements")
    op.drop_table("line_measurements")
    op.drop_index(
        "ix_line_capacity_slots_organization_id_factory_id", table_name="line_capacity_slots"
    )
    op.drop_table("line_capacity_slots")
    op.drop_table("line_capabilities")
    op.drop_table("import_errors")
    op.drop_index("ix_document_versions_document_id_status", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_table("document_acl")
    op.drop_table("bom_lines")
    op.drop_table("style_operations")
    op.drop_table("role_assignments")
    op.drop_index("ix_notifications_organization_id_factory_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_notes_organization_id_factory_id", table_name="notes")
    op.drop_table("notes")
    op.drop_index("ix_material_lots_organization_id_factory_id", table_name="material_lots")
    op.drop_table("material_lots")
    op.drop_index("ix_material_balances_organization_id_factory_id", table_name="material_balances")
    op.drop_table("material_balances")
    op.drop_index("ix_lines_organization_id_factory_id", table_name="lines")
    op.drop_table("lines")
    op.drop_index(
        "uq_import_batches_organization_id_kind_file_sha256",
        table_name="import_batches",
        postgresql_where=sa.text("status = 'COMMITTED'"),
    )
    op.drop_index("ix_import_batches_organization_id_factory_id", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_expected_receipts_organization_id_factory_id", table_name="expected_receipts")
    op.drop_table("expected_receipts")
    op.drop_index("ix_documents_organization_id_factory_id", table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        "uq_bom_versions_one_active_per_style",
        table_name="bom_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("bom_versions")
    op.drop_table("styles")
    op.drop_table("sessions")
    op.drop_table("quality_policy_versions")
    op.drop_table("memberships")
    op.drop_table("materials")
    op.drop_table("idempotency_keys")
    op.drop_table("factories")
    op.drop_table("customers")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_index("ix_jobs_queue_status_available_at", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_audit_events_organization_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_organization_id_factory_id", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
