import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router'

import { DataTable, type Column } from '../../components/DataTable'
import { EmptyState } from '../../components/EmptyState'
import { StateBadge } from '../../components/StateBadge'
import { api, unwrap, type Schemas } from '../../lib/api'
import { useFactory } from '../../lib/factory'
import { formatDate, formatDecimal, formatPercent } from '../../lib/format'
import { parseOrderReport } from './orderReport'

type Allocation = Schemas['AllocationOut']
type SlotDiff = Schemas['SlotDiffOut']

const COMMITTED_COLUMNS: Column<Allocation>[] = [
  { key: 'slot_id', header: 'Slot', render: (row) => <span className="font-mono text-xs">{row.slot_id.slice(0, 8)}</span> },
  { key: 'units', header: 'Units', align: 'right', render: (row) => formatDecimal(row.units, 0) },
  {
    key: 'standard_minutes',
    header: 'Standard minutes',
    align: 'right',
    render: (row) => formatDecimal(row.standard_minutes),
  },
  { key: 'status', header: 'Status', render: (row) => row.status },
]

const PROPOSED_COLUMNS: Column<SlotDiff>[] = [
  { key: 'line_code', header: 'Line', render: (row) => <span className="font-bold text-fg">{row.line_code}</span> },
  { key: 'slot_date', header: 'Date', render: (row) => formatDate(row.slot_date) },
  { key: 'shift_code', header: 'Shift', render: (row) => row.shift_code },
  {
    key: 'allocated_after',
    header: 'Proposed Units',
    align: 'right',
    render: (row) => <span className="font-semibold text-fg tabular-nums">{formatDecimal(row.allocated_after, 0)}</span>,
  },
  {
    key: 'remaining_after',
    header: 'Remaining Capacity',
    align: 'right',
    render: (row) => <span className="tabular-nums text-fg-muted">{formatDecimal(row.remaining_after, 0)}</span>,
  },
  {
    key: 'utilization_after',
    header: 'Utilization',
    align: 'right',
    render: (row) => {
      const fraction = row.utilization_after === null ? null : Number(row.utilization_after)
      return <span className="tabular-nums font-medium">{formatPercent(fraction)}</span>
    },
  },
]

/** The order's capacity plan: displays AI proposed allocation & live committed allocations. */
export function OrderPlanTab({ order }: { order: Schemas['OrderDetail'] }) {
  const factory = useFactory()
  const report = parseOrderReport(order.latest_report)
  const recommendationId = report?.recommendation?.id

  const recQuery = useQuery({
    queryKey: ['recommendation', recommendationId],
    queryFn: () =>
      unwrap(
        api.GET('/api/v1/recommendations/{rec_id}', {
          params: { path: { rec_id: recommendationId! } },
        }),
      ),
    enabled: Boolean(recommendationId),
  })

  const planningSummary = report?.agentSummaries?.find((s) => s.agent === 'planning')
  const proposalSlots = recQuery.data?.diff?.slots ?? []
  const hasProposal = Boolean(recommendationId || planningSummary)
  const isCommitted = (order.allocations?.length ?? 0) > 0

  return (
    <div className="flex flex-col gap-6">
      {/* 1. Proposed AI Production Plan */}
      {hasProposal && (
        <section className="flex flex-col gap-4 rounded-xl border border-line bg-surface p-5 shadow-xs">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line pb-3">
            <div className="flex items-center gap-2.5">
              <span className="text-xl" role="img" aria-label="AI Plan">
                🤖
              </span>
              <div>
                <h3 className="text-base font-bold text-fg">AI Proposed Production Plan</h3>
                <span className="text-xs text-fg-muted">
                  Generated by Planning Agent · Grounded in live line capacity
                </span>
              </div>
            </div>
            {report?.recommendation && (
              <div className="flex items-center gap-2">
                <StateBadge vocabulary="recommendation" state={report.recommendation.status} />
                <Link
                  to={`/f/${encodeURIComponent(factory.code)}/approvals/${encodeURIComponent(report.recommendation.id)}`}
                  className="btn-primary text-xs h-8 px-3 inline-flex items-center gap-1.5 shadow-xs"
                >
                  <span>Review in Approvals</span>
                  <span aria-hidden="true">&rarr;</span>
                </Link>
              </div>
            )}
          </div>

          {/* Verdict and Plan Takeaway */}
          <div className="rounded-lg border border-success-line bg-success-bg/20 p-4">
            <div className="flex items-center gap-2">
              <span className="text-xl" role="img" aria-label="Success">
                ✅
              </span>
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-fg-muted block">The Verdict</span>
                <h4 className="text-sm font-bold text-fg">It can be done on time!</h4>
              </div>
            </div>
            <p className="text-sm font-semibold text-fg mt-2">
              {planningSummary?.summary || recQuery.data?.rationale || 'Optimal line allocation proposal computed.'}
            </p>
          </div>

          {/* Proposed Capacity Slots */}
          {proposalSlots.length > 0 && (
            <div className="flex flex-col gap-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-fg-muted">
                Proposed Line Allocation Schedule
              </h4>
              <DataTable
                caption="Proposed Capacity Slots"
                columns={PROPOSED_COLUMNS}
                rows={proposalSlots}
                rowKey={(row) => row.slot_id}
              />
            </div>
          )}

          {!isCommitted && (
            <div className="rounded-md border border-line bg-surface-sunken/60 px-3.5 py-2.5 text-xs text-fg-muted flex items-center justify-between">
              <span>
                💡 This plan is currently awaiting supervisor approval. Once approved in Approvals Inbox, these slots will be permanently committed to the capacity board.
              </span>
            </div>
          )}
        </section>
      )}

      {/* 2. Committed Live Allocations */}
      {isCommitted ? (
        <section className="flex flex-col gap-2">
          <h3 className="text-base font-semibold text-fg">Committed Allocations</h3>
          <DataTable
            caption="Allocations"
            columns={COMMITTED_COLUMNS}
            rows={order.allocations ?? []}
            rowKey={(row) => row.id}
          />
        </section>
      ) : (
        !hasProposal && (
          <EmptyState
            icon="calendar"
            title="No allocations yet"
            description="This order has not been scheduled on the capacity board yet. Run an analysis above to generate an AI plan."
          />
        )
      )}
    </div>
  )
}

