"""Domain vocabularies shared by the ORM models and business logic.

Every ``StrEnum`` here backs a Postgres ``CHECK`` constraint generated by
``app.db.types.enum_check`` so that a column's allowed values live in exactly
one place: change the enum, regenerate the migration, and the check
constraint follows. See ``docs/architecture/backend-contracts.md`` section 3
for the vocabularies that are part of the binding API/DB contract, and
section 2 for the smaller per-table enumerations (statuses, kinds, etc.)
that are local to a single column.
"""

from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    """`app/auth/policy.py` roles (backend-contracts.md section 4)."""

    ORG_ADMIN = "org_admin"
    SUPERVISOR = "supervisor"
    PLANNER = "planner"
    STOREKEEPER = "storekeeper"
    IE_ENGINEER = "ie_engineer"
    QUALITY_MANAGER = "quality_manager"
    VIEWER = "viewer"


class ProductionState(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    PLANNED = "PLANNED"
    IN_PRODUCTION = "IN_PRODUCTION"
    PRODUCTION_COMPLETE = "PRODUCTION_COMPLETE"
    DISPATCHED = "DISPATCHED"
    CANCELLED = "CANCELLED"


class MaterialState(StrEnum):
    UNKNOWN = "UNKNOWN"
    READY = "READY"
    AT_RISK = "AT_RISK"
    SHORTAGE = "SHORTAGE"


class QualityState(StrEnum):
    NOT_INSPECTED = "NOT_INSPECTED"
    PENDING = "PENDING"
    HOLD = "HOLD"
    RELEASED = "RELEASED"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    AWAITING_REVIEW = "AWAITING_REVIEW"
    COMPLETED = "COMPLETED"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


# The ``run_events.event_type`` of the canonical per-order report an analysis
# run finalizes into (written by ``app.orchestration.synthesis``, read by the
# run detail API and the order detail's ``latest_report``).
REPORT_EVENT_TYPE = "run.report"


class RecommendationStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    APPLIED = "APPLIED"
    SUPERSEDED = "SUPERSEDED"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobStatus(StrEnum):
    READY = "READY"
    LEASED = "LEASED"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MaterialUnit(StrEnum):
    METER = "m"
    KILOGRAM = "kg"
    PIECE = "pcs"
    CONE = "cone"


class OrderSource(StrEnum):
    MANUAL = "manual"
    CSV_IMPORT = "csv_import"
    SYNTHETIC_SEED = "synthetic_seed"


class ShiftCode(StrEnum):
    A = "A"
    B = "B"


class AllocationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"


class MaterialLotStatus(StrEnum):
    QUARANTINE = "QUARANTINE"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class MovementType(StrEnum):
    RECEIPT = "RECEIPT"
    ISSUE = "ISSUE"
    CORRECTION = "CORRECTION"


class ReservationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    CONSUMED = "CONSUMED"


class ExpectedReceiptStatus(StrEnum):
    OPEN = "OPEN"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class PolicyStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class InspectionType(StrEnum):
    INLINE = "INLINE"
    FINAL = "FINAL"


class InspectionResult(StrEnum):
    PASS_ = "PASS"  # noqa: S105 (an inspection result, not a credential)
    FAIL = "FAIL"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"


class DefectSeverity(StrEnum):
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"


class QualityHoldStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"


class DocumentType(StrEnum):
    SOP = "SOP"
    QUALITY_POLICY = "QUALITY_POLICY"
    IE_STANDARD = "IE_STANDARD"
    OTHER = "OTHER"


class DocumentVersionStatus(StrEnum):
    QUARANTINE = "QUARANTINE"
    PROCESSING = "PROCESSING"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class AgentRecipient(StrEnum):
    PLANNING = "planning"
    RM = "rm"
    IE = "ie"
    QUALITY = "quality"


class RecommendationKind(StrEnum):
    ALLOCATION = "ALLOCATION"
    RESERVATION = "RESERVATION"
    ALLOCATION_AND_RESERVATION = "ALLOCATION_AND_RESERVATION"


class GeneratedBy(StrEnum):
    DETERMINISTIC = "deterministic"
    MODEL = "model"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ActorType(StrEnum):
    USER = "USER"
    SERVICE = "SERVICE"
    SYSTEM = "SYSTEM"


class AuditOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    DENIED = "DENIED"
    FAILED = "FAILED"


class ImportBatchStatus(StrEnum):
    VALIDATED = "VALIDATED"
    COMMITTED = "COMMITTED"
    REJECTED = "REJECTED"


ROLES: tuple[str, ...] = tuple(role.value for role in Role)
