#!/usr/bin/env python3
"""Generate docs/security/role-matrix.md from app.auth.policy.PERMISSIONS
(task-25-brief.md req. 11), so the two can never drift apart.

Run from the backend so `app` is importable:

    cd services/backend && uv run python ../../scripts/gen_role_matrix.py

Output is deterministic (sorted permissions/roles), so re-running it against
an unchanged policy rewrites a byte-identical file; `docs-check`-style CI can
therefore diff the committed file against a fresh run to catch drift.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "services" / "backend"
OUTPUT_FILE = REPO_ROOT / "docs" / "security" / "role-matrix.md"

sys.path.insert(0, str(BACKEND_DIR))

from app.auth.policy import PERMISSIONS  # noqa: E402
from app.domain.vocab import ROLES  # noqa: E402

GENERATED_NOTICE = (
    "<!-- GENERATED by scripts/gen_role_matrix.py from app.auth.policy.PERMISSIONS. "
    "Do not hand-edit; re-run the script instead. -->"
)


def render() -> str:
    roles = sorted(ROLES)
    permissions = sorted(PERMISSIONS)
    now = datetime.now(tz=UTC).strftime("%Y-%m-%d")

    header = "| Permission | " + " | ".join(roles) + " |"
    separator = "|---|" + "|".join("---" for _ in roles) + "|"
    rows = []
    for permission in permissions:
        allowed = PERMISSIONS[permission]
        cells = ["x" if role in allowed else "" for role in roles]
        rows.append(f"| `{permission}` | " + " | ".join(cells) + " |")

    lines = [
        GENERATED_NOTICE,
        "",
        "# Role permission matrix",
        "",
        f"Generated {now} from `app.auth.policy.PERMISSIONS`"
        " (backend-contracts.md section 4). Regenerate with:",
        "",
        "```",
        "cd services/backend && uv run python ../../scripts/gen_role_matrix.py",
        "```",
        "",
        header,
        separator,
        *rows,
        "",
        "`org_admin` gets exactly the permissions listed for it above (plus the",
        "all-roles read set); it has no implicit business authority beyond that --",
        "notably it cannot decide or apply a recommendation, transition an order,",
        "or write inventory/IE/quality records.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
