#!/usr/bin/env bash
# Regenerate docs/assessment/licenses.md from the two lockfiles.
#
# Backend : uv run --with pip-licenses pip-licenses --from=mixed --format=markdown
#           (run inside services/backend). `uvx pip-licenses` was tried first
#           and produced an EMPTY table: uvx runs the tool in its own isolated
#           environment, and pip-licenses reads the *running* interpreter's
#           installed distributions. `uv run --with` layers the tool over the
#           project's own virtualenv, so it sees the real dependency set.
# Frontend: npx license-checker --summary                    (run inside apps/web)
#
# Both tools are fetched on demand (uv / npx) and are not project
# dependencies. Network access is required. Wrap the call in
# scripts/heavy-job.sh when other agents may be running heavy work:
#
#   scripts/heavy-job.sh bash scripts/gen_licenses.sh
#
# The generated file keeps its hand-written header and "Other components"
# section, which are re-emitted here (pgvector, the fastembed model, the
# synthetic corpus statement) -- edit them in this script, not in the
# generated Markdown, or the next run will drop them.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo_root/docs/assessment/licenses.md"
generated_at="$(date -u +%Y-%m-%d)"

command -v uv >/dev/null || { echo "gen_licenses: uv not found" >&2; exit 1; }
command -v npx >/dev/null || { echo "gen_licenses: npx not found (install Node)" >&2; exit 1; }

backend_md="$(cd "$repo_root/services/backend" \
  && uv run --with pip-licenses pip-licenses --from=mixed --format=markdown)"
web_summary="$(cd "$repo_root/apps/web" && npx --yes license-checker --summary 2>/dev/null)"

{
  cat <<EOF
# Third-party licences

Generated by \`scripts/gen_licenses.sh\` on ${generated_at} from the two
committed lockfiles (\`services/backend/uv.lock\`, \`apps/web/package-lock.json\`).
Regenerate with:

\`\`\`bash
bash scripts/gen_licenses.sh
# or, when other heavy jobs may be running:
scripts/heavy-job.sh bash scripts/gen_licenses.sh
\`\`\`

The two tables below are verbatim tool output — \`uv run --with pip-licenses
pip-licenses --from=mixed --format=markdown\` for the backend environment and
\`npx license-checker --summary\` for the web workspace. Nothing in them is
hand-edited; correct a wrong entry at its source (the package's own
metadata) and re-run. (\`uvx pip-licenses\` is *not* used: uvx isolates the
tool from the project's virtualenv, so it reports an empty table.)

A licence string here is whatever the package's own metadata declares; a few
packages declare a classifier phrase ("MIT License", "BSD License") rather
than an SPDX identifier, and a small number declare nothing at all
(\`UNKNOWN\`). Those are not licence problems by themselves — they are
metadata gaps — but any \`UNKNOWN\` row should be resolved against the
package's repository before a commercial release.

## Backend (Python, \`services/backend\`)

${backend_md}

## Frontend (npm, \`apps/web\`)

\`npx license-checker --summary\` reports one line per distinct licence across
the installed dependency tree (production **and** development, which is what
the plain \`--summary\` invocation covers):

\`\`\`
${web_summary}
\`\`\`

### Triage note (checked 2026-09-20)

One backend row reported \`UNKNOWN\`: **\`py_rust_stemmers\`** (a transitive
dependency of \`fastembed\`). Its wheel metadata declares no licence field.
This is an unresolved metadata gap, recorded here rather than silently
ignored: confirm the licence from the project's own repository before any
commercial distribution. Every other row carries a declared licence, and the
web summary above contains one \`UNLICENSED\` entry, which is \`apps/web\`
itself (\`"private": true\` in \`package.json\`) — not a third-party package.

## Other components not covered by either lockfile

| Component | Version | Licence | Where used |
|---|---|---|---|
| PostgreSQL | 16 (project-local cluster, port 55432) | PostgreSQL License | The only datastore (\`scripts/dev-db.sh\`, \`infra/compose/docker-compose.yml\`) |
| pgvector | 0.8.6 | PostgreSQL License | \`vector\` extension for chunk embeddings (ADR-0002) |
| \`BAAI/bge-small-en-v1.5\` (embedding model, downloaded at first use by fastembed) | 1.5 | MIT | \`app/retrieval/embedder.py\` (\`FastEmbedEmbedder\`, 384 dimensions) |
| Keycloak (container image, statically validated only — never run here) | 26.7.4 | Apache-2.0 | \`infra/identity/keycloak/\` |
| Caddy (container image, statically validated only — never run here) | 2.11-alpine | Apache-2.0 | \`infra/proxy/Caddyfile\` |

## Project-original content

The synthetic SOP corpus (\`data/synthetic/sops/\`, 30 documents plus one
superseded version), the adversarial fixtures (\`data/synthetic/adversarial/\`),
and the labelled evaluation datasets (\`data/eval/notes_train.jsonl\`,
\`notes_test.jsonl\`, \`retrieval_questions.jsonl\`) are **original to this
project**. They were authored for it, contain no copied third-party text, and
describe no real factory, customer, worker or product. They are synthetic
demonstration data and must never be presented as real factory data
(\`docs/evaluation/synthetic-data.md\`, \`data/synthetic/README.md\`,
\`data/eval/README.md\`).

The repository's own source code is covered by the licence named in
\`README.md\`.
EOF
} > "$out"

echo "gen_licenses: wrote $out"
